# Pandas Introduction: A Complete Guide

Welcome to your comprehensive introduction to Pandas! This notebook will guide you through all the essential concepts of Pandas, from basic operations to advanced techniques.

## What You'll Learn:
1. **Introduction** - What is Pandas and why use it?
2. **Getting Started** - Loading and displaying data
3. **Basic Operations** - Exploring and selecting data
4. **Data Cleaning** - Handling missing values and data types
5. **Filtering & Sorting** - Finding and organizing data
6. **GroupBy & Aggregations** - Summarizing data by groups
7. **Merging & Joining** - Combining datasets
8. **Advanced Operations** - Apply functions and pivot tables

Let's dive in!

## 1. Introduction

### What is Pandas?

**Pandas** (Python Data Analysis Library) is a powerful, open-source data manipulation and analysis library for Python. It provides data structures and functions needed to work with structured data seamlessly.

### Why Use Pandas?

Let's compare working with raw Python vs. Pandas to see why Pandas is essential for data science:

**Raw Python approach:**
```python
# Working with election data using raw Python
data = [
    ['Reagan', 'Republican', 50.7, 1980, 'win'],
    ['Carter', 'Democratic', 41.0, 1980, 'loss'],
    ['Anderson', 'Independent', 6.6, 1980, 'loss']
]

# To find all winners, you'd need to:
winners = []
for row in data:
    if row[4] == 'win':
        winners.append(row)
```

**Pandas approach:**
```python
# Much simpler with Pandas!
winners = elections[elections['Result'] == 'win']
```

### Key Advantages of Pandas:
- **Intuitive**: Easy-to-use data structures (DataFrame, Series)
- **Powerful**: Built-in functions for data cleaning, transformation, and analysis  
- **Efficient**: Optimized for performance with large datasets
- **Flexible**: Handles missing data, different data types, and complex operations
- **Integration**: Works seamlessly with other Python libraries (NumPy, Matplotlib, etc.)

## 2. Getting Started

Let's start by importing the necessary libraries and loading our dataset.

In [1]:
# !pip install pandas
# !pip install numpy
# !pip install matplotlib

# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Set up plotting style (optional)
plt.style.use('fivethirtyeight')

print("Libraries imported successfully!")
print("Pandas version:", pd.__version__)

Libraries imported successfully!
Pandas version: 2.3.2

### Loading Data from CSV

The most common way to get data into Pandas is by reading from a CSV file using `pd.read_csv()`. Let's load our US Presidential Election dataset.

In [2]:
# Load the elections dataset
elections = pd.read_csv("elections.csv")

# Display the DataFrame
elections  # When a cell ends with a variable name, Jupyter displays it

   Candidate        Party     %  Year Result
0     Reagan   Republican  50.7  1980    win
1     Carter   Democratic  41.0  1980   loss
2   Anderson  Independent   6.6  1980   loss
3     Reagan   Republican  58.8  1984    win
4    Mondale   Democratic  37.6  1984   loss
5       Bush   Republican  53.4  1988    win
6    Dukakis   Democratic  45.6  1988   loss
7    Clinton   Democratic  43.0  1992    win
8       Bush   Republican  37.4  1992   loss
9      Perot  Independent  18.9  1992   loss
10   Clinton   Democratic  49.2  1996    win
11      Dole   Republican  40.7  1996   loss
12     Perot  Independent   8.4  1996   loss
13      Gore   Democratic  48.4  2000   loss
14      Bush   Republican  47.9  2000    win
15     Kerry   Democratic  48.3  2004   loss
16      Bush   Republican  50.7  2004    win
17     Obama   Democratic  52.9  2008    win
18    McCain   Republican  45.7  2008   loss
19     Obama   Democratic  51.1  2012    win
20    Romney   Republican  47.2  2012   loss
21   Clinton   Democratic  48.2  2016   loss
22     Trump   Republican  46.1  2016    win

### Displaying Data

Pandas provides several methods to quickly view your data:

- `head()` - Shows the first few rows (default: 5)
- `tail()` - Shows the last few rows  
- `sample()` - Shows random rows

Let's try these:

In [3]:
# Show first 3 rows
print("First 3 rows:")
elections.head(3)

First 3 rows:

  Candidate        Party     %  Year Result
0    Reagan   Republican  50.7  1980    win
1    Carter   Democratic  41.0  1980   loss
2  Anderson  Independent   6.6  1980   loss

In [4]:
# Show last 2 rows
print("Last 2 rows:")
elections.tail(2)

Last 2 rows:

   Candidate       Party     %  Year Result
21   Clinton  Democratic  48.2  2016   loss
22     Trump  Republican  46.1  2016    win

### 🤔 Your Turn: Practice with Display Methods

**Task 1:** Use the `sample()` method to display 3 random rows from the elections dataset.

**Task 2:** Try using `head()` without any arguments. How many rows does it show by default?

In [5]:
# Task 1: YOUR CODE HERE - show 3 random rows
elections.sample(3)

   Candidate       Party     %  Year Result
13      Gore  Democratic  48.4  2000   loss
17     Obama  Democratic  52.9  2008    win
0     Reagan  Republican  50.7  1980    win

In [6]:
# Task 2: YOUR CODE HERE - use head() with no arguments
elections.head()

  Candidate        Party     %  Year Result
0    Reagan   Republican  50.7  1980    win
1    Carter   Democratic  41.0  1980   loss
2  Anderson  Independent   6.6  1980   loss
3    Reagan   Republican  58.8  1984    win
4   Mondale   Democratic  37.6  1984   loss

## 3. Basic Operations

Now that we have our data loaded, let's explore it! Understanding your dataset is the first step in any data analysis.

### Exploring Dataset Properties

Let's learn about our dataset using these essential methods:

- `shape` - Dimensions (rows, columns)
- `size` - Total number of elements  
- `info()` - Data types and memory usage
- `describe()` - Statistical summary
- `columns` - Column names

In [7]:
# Dataset dimensions
print("Shape (rows, columns):", elections.shape)
print("Total elements:", elections.size)
print("Column names:", list(elections.columns))

Shape (rows, columns): (23, 5)
Total elements: 115
Column names: ['Candidate', 'Party', '%', 'Year', 'Result']

In [8]:
# Get detailed information about the dataset
elections.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Candidate  23 non-null     object
 1   Party      23 non-null     object
 2   %          23 non-null     float64
 3   Year       23 non-null     int64
 4   Result     23 non-null     object
dtypes: float64(1), int64(1), object(3)
memory usage: 1.0+ KB

In [9]:
# Statistical summary for numerical columns
elections.describe()

               %         Year
count  23.000000    23.000000
mean   42.513043  1996.869565
std    13.476117    11.627961
min     6.600000  1980.000000
25%    40.850000  1988.000000
50%    47.200000  1996.000000
75%    49.950000  2006.000000
max    58.800000  2016.000000

### Selecting Columns and Rows

The `[]` operator is your main tool for selecting data. Let's learn different ways to select columns and rows.

In [10]:
# Select a single column (returns a Series)
print("Single column (Candidate):")
print(elections["Candidate"].head(3))
print(f"Type: {type(elections['Candidate'])}")

Single column (Candidate):
0      Reagan
1      Carter
2    Anderson
Name: Candidate, dtype: object
Type: <class 'pandas.core.series.Series'>

In [11]:
# Select multiple columns (returns a DataFrame)
print("Multiple columns:")
elections[["Candidate", "Party", "%"]].head(3)

Multiple columns:

  Candidate        Party     %
0    Reagan   Republican  50.7
1    Carter   Democratic  41.0
2  Anderson  Independent   6.6

In [12]:
# Select rows by position using slicing
print("Rows 2-4 (using slicing):")
elections[2:5]  # Remember: end index is exclusive

Rows 2-4 (using slicing):

  Candidate        Party     %  Year Result
2  Anderson  Independent   6.6  1980   loss
3    Reagan   Republican  58.8  1984    win
4   Mondale   Democratic  37.6  1984   loss

### Advanced Selection: .loc and .iloc

For more precise control, Pandas provides `.loc` (label-based) and `.iloc` (position-based) indexers.

In [13]:
# .loc[row_indexer, column_indexer] - uses labels
print("Using .loc - specific rows and columns:")
elections.loc[0:2, ['Candidate', 'Party']]  # Rows 0-2, specific columns

Using .loc - specific rows and columns:

  Candidate        Party
0    Reagan   Republican
1    Carter   Democratic
2  Anderson  Independent

In [14]:
# .iloc[row_indexer, column_indexer] - uses integer positions
print("Using .iloc - by position:")
elections.iloc[0:3, 0:2]  # First 3 rows, first 2 columns

Using .iloc - by position:

  Candidate        Party
0    Reagan   Republican
1    Carter   Democratic
2  Anderson  Independent

### Adding and Dropping Columns

You can easily add new columns or remove existing ones.

In [15]:
# Add a new column
elections['Vote_Percentage_Decimal'] = elections['%'] / 100

# Show the result
print("Added new column:")
elections[['Candidate', '%', 'Vote_Percentage_Decimal']].head(3)

Added new column:

  Candidate     %  Vote_Percentage_Decimal
0    Reagan  50.7                    0.507
1    Carter  41.0                    0.410
2  Anderson   6.6                    0.066

In [16]:
# Drop a column (create a copy without the column)
elections_no_decimal = elections.drop('Vote_Percentage_Decimal', axis=1)

print("Columns after dropping:")
print(list(elections_no_decimal.columns))

Columns after dropping:
['Candidate', 'Party', '%', 'Year', 'Result']

### 🤔 Your Turn: Practice Selection and Column Operations

**Task 1:** Select only the 'Candidate', 'Year', and 'Result' columns and display the first 4 rows.

**Task 2:** Use `.iloc` to select the last 3 rows and first 2 columns.

**Task 3:** Create a new column called 'Decade' that shows which decade each election was in (e.g., 1980s, 1990s, etc.).

*Hint for Task 3: You can use `elections['Year'] // 10 * 10` to get the decade start year, then add 's' to make it '1980s'*

In [17]:
# Task 1: YOUR CODE HERE - Select specific columns and show first 4 rows
elections[['Candidate', 'Year', 'Result']].head(4)

# Task 2: YOUR CODE HERE - Use iloc for last 3 rows, first 2 columns  
elections.iloc[-3:, :2]

# Task 3: YOUR CODE HERE - Create 'Decade' column
elections['Decade'] = elections['%'] / 100

## 4. Data Cleaning

Real-world data is rarely perfect. Let's learn essential techniques for cleaning and preparing data for analysis.

### Handling Missing Values

Let's create some missing data to demonstrate cleaning techniques, since our elections dataset is clean.

In [18]:
# Create a copy of elections data and introduce some missing values for demonstration
elections_dirty = elections.copy()

# Introduce some NaN values
elections_dirty.loc[1, 'Candidate'] = np.nan
elections_dirty.loc[5, '%'] = np.nan
elections_dirty.loc[8, 'Party'] = np.nan

print("Dataset with missing values:")
elections_dirty.head(10)

Dataset with missing values:

  Candidate        Party     %  Year Result  Vote_Percentage_Decimal  Decade
0    Reagan   Republican  50.7  1980    win                    0.507   0.507
1       NaN   Democratic  41.0  1980   loss                    0.410   0.410
2  Anderson  Independent   6.6  1980   loss                    0.066   0.066
3    Reagan   Republican  58.8  1984    win                    0.588   0.588
4   Mondale   Democratic  37.6  1984   loss                    0.376   0.376
5      Bush   Republican   NaN  1988    win                    0.534   0.534
6   Dukakis   Democratic  45.6  1988   loss                    0.456   0.456
7   Clinton   Democratic  43.0  1992    win                    0.430   0.430
8      Bush          NaN  37.4  1992   loss                    0.374   0.374
9     Perot  Independent  18.9  1992   loss                    0.189   0.189

In [19]:
# Check for missing values
print("Missing values per column:")
print(elections_dirty.isnull().sum())

print("\nRows with any missing values:")
print(elections_dirty[elections_dirty.isnull().any(axis=1)])

Missing values per column:
Candidate                  1
Party                      1
%                          1
Year                       0
Result                     0
Vote_Percentage_Decimal    0
Decade                     0
dtype: int64

Rows with any missing values:
  Candidate       Party     %  Year Result  Vote_Percentage_Decimal  Decade
1       NaN  Democratic  41.0  1980   loss                    0.410   0.410
5      Bush  Republican   NaN  1988    win                    0.534   0.534
8      Bush         NaN  37.4  1992   loss                    0.374   0.374

In [20]:
# Method 1: Drop rows with missing values
print("Original shape:", elections_dirty.shape)
elections_dropped = elections_dirty.dropna()
print("After dropping rows with NaN:", elections_dropped.shape)

Original shape: (23, 7)
After dropping rows with NaN: (20, 7)

In [21]:
# Method 2: Fill missing values
elections_filled = elections_dirty.copy()

# Fill missing candidate names with "Unknown"
elections_filled['Candidate'].fillna("Unknown", inplace=True)

# Fill missing percentages with the mean
mean_percentage = elections_filled['%'].mean()
elections_filled['%'].fillna(mean_percentage, inplace=True)

# Fill missing parties with "Independent"  
elections_filled['Party'].fillna("Independent", inplace=True)

print("After filling missing values:")
elections_filled[elections_filled.index.isin([1, 5, 8])]

After filling missing values:

C:\Users\Dell\AppData\Local\Temp\ipykernel_18800\1435566039.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  elections_filled['Candidate'].fillna("Unknown", inplace=True)
C:\Users\Dell\AppData\Local\Temp\ipykernel_18800\1435566039.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  elections_filled['%'].fillna(mean_percentage, inplace=True)
C:\Users\Dell\AppData\Local\Temp\ipykernel_18800\1435566039.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  elections_filled['Party'].fillna("Independent", inplace=True)

,Candidate,Party,%,Year,Result,Vote_Percentage_Decimal,Decade
1,Unknown,Democratic,41.000000,1980,loss,0.410,0.410
5,Bush,Republican,42.018182,1988,win,0.534,0.534
8,Bush,Independent,37.400000,1992,loss,0.374,0.374

### Renaming Columns

Sometimes column names need to be more descriptive or follow naming conventions.

In [22]:
# Rename columns
elections_renamed = elections.rename(columns={
    '%': 'Vote_Percentage',
    'Candidate': 'Candidate_Name'
})

print("Renamed columns:")
print(list(elections_renamed.columns))

Renamed columns:
['Candidate_Name', 'Party', 'Vote_Percentage', 'Year', 'Result', 'Vote_Percentage_Decimal', 'Decade']

### Changing Data Types

Ensuring columns have the correct data type is crucial for analysis.

In [23]:
# Check current data types
print("Current data types:")
print(elections.dtypes)

# Convert Year to string (category)
elections_types = elections.copy()
elections_types['Year'] = elections_types['Year'].astype(str)

print("\nAfter converting Year to string:")
print(elections_types.dtypes)

Current data types:
Candidate                   object
Party                       object
%                          float64
Year                         int64
Result                      object
Vote_Percentage_Decimal    float64
Decade                     float64
dtype: object

After converting Year to string:
Candidate                   object
Party                       object
%                          float64
Year                        object
Result                      object
Vote_Percentage_Decimal    float64
Decade                     float64
dtype: object

### 🤔 Your Turn: Practice Data Cleaning

**Task 1:** Create a DataFrame with some missing values and practice using `dropna()` and `fillna()`.

**Task 2:** Rename the 'Result' column to 'Election_Result' in the elections dataset.

**Task 3:** Convert the 'Party' column to a categorical data type using `astype('category')`.

In [24]:
# Task 1: YOUR CODE HERE - Create DataFrame with missing values and practice cleaning
data = {
    'Candidate': ['Alice', 'Bob', 'Charlie', None, 'Eve'],
    'Party': ['A', 'B', None, 'C', 'A'],
    'Result': [1000, 850, None, 400, 1200]
}
elections = pd.DataFrame(data)

print("Original DataFrame with Missing Values:")
print(elections)
cleaned_dropna = elections.dropna()

# Fill missing values
cleaned_fillna = elections.fillna({
    'Candidate': 'Unknown',
    'Party': 'Independent',
    'Result': 0
})

# Task 2: YOUR CODE HERE - Rename 'Result' column
elections_renamed = elections.rename(columns={
    'Result': 'New_result',
})


# Task 3: YOUR CODE HERE - Convert 'Party' to categorical
elections['Party'] = elections['Party'].astype('category')

Original DataFrame with Missing Values:
  Candidate Party  Result
0     Alice     A  1000.0
1       Bob     B   850.0
2   Charlie  None     NaN
3      None     C   400.0
4       Eve     A  1200.0

## 5. Filtering & Sorting

One of the most powerful features of Pandas is the ability to filter and sort data efficiently.

### Boolean Filtering

Use boolean conditions to filter rows that meet specific criteria.

In [25]:
# Filter for winners only
winners = elections[elections['Result'] == 'win']
print("Election winners:")
print(winners[['Candidate', 'Party', 'Year', '%']])

Election winners:

KeyError: "['Year', '%'] not in index"

In [ ]:
# Filter for high vote percentages (> 50%)
high_votes = elections[elections['%'] > 50]
print("Candidates with >50% of votes:")
print(high_votes[['Candidate', 'Party', 'Year', '%']])

Candidates with >50% of votes:
   Candidate       Party  Year     %
0     Reagan  Republican  1980  50.7
3     Reagan  Republican  1984  58.8
5       Bush  Republican  1988  53.4
16      Bush  Republican  2004  50.7
17     Obama  Democratic  2008  52.9
19     Obama  Democratic  2012  51.1

In [ ]:
# Multiple conditions - use & (and) or | (or)
# Winners who got less than 50% of the vote
narrow_winners = elections[(elections['Result'] == 'win') & (elections['%'] < 50)]
print("Winners with <50% of votes:")
print(narrow_winners[['Candidate', 'Party', 'Year', '%']])

Winners with <50% of votes:
   Candidate       Party  Year     %
7    Clinton  Democratic  1992  43.0
10   Clinton  Democratic  1996  49.2
14      Bush  Republican  2000  47.9
22     Trump  Republican  2016  46.1

In [ ]:
# Filter using .isin() for multiple values
parties_of_interest = ['Democratic', 'Republican']
major_parties = elections[elections['Party'].isin(parties_of_interest)]
print("Major party candidates:")
print(major_parties.head())

Major party candidates:
  Candidate       Party     %  Year Result
0    Reagan  Republican  50.7  1980    win
1    Carter  Democratic  41.0  1980   loss
3    Reagan  Republican  58.8  1984    win
4   Mondale  Democratic  37.6  1984   loss
5      Bush  Republican  53.4  1988    win

### Sorting Data

Sort your data by one or more columns to find patterns and insights.

In [ ]:
# Sort by vote percentage (ascending)
sorted_by_votes = elections.sort_values('%')
print("Sorted by vote percentage (lowest first):")
print(sorted_by_votes[['Candidate', 'Party', 'Year', '%']].head())

Sorted by vote percentage (lowest first):
   Candidate        Party  Year     %
2   Anderson  Independent  1980   6.6
12     Perot  Independent  1996   8.4
9      Perot  Independent  1992  18.9
8       Bush   Republican  1992  37.4
4    Mondale   Democratic  1984  37.6

In [ ]:
# Sort by vote percentage (descending)
sorted_desc = elections.sort_values('%', ascending=False)
print("Sorted by vote percentage (highest first):")
print(sorted_desc[['Candidate', 'Party', 'Year', '%']].head())

Sorted by vote percentage (highest first):
   Candidate       Party  Year     %
3     Reagan  Republican  1984  58.8
5       Bush  Republican  1988  53.4
17     Obama  Democratic  2008  52.9
19     Obama  Democratic  2012  51.1
16      Bush  Republican  2004  50.7

In [ ]:
# Sort by multiple columns
multi_sort = elections.sort_values(['Year', '%'], ascending=[True, False])
print("Sorted by Year (ascending) then Vote % (descending):")
print(multi_sort[['Candidate', 'Party', 'Year', '%']].head(8))

Sorted by Year (ascending) then Vote % (descending):
  Candidate        Party  Year     %
0    Reagan   Republican  1980  50.7
1    Carter   Democratic  1980  41.0
2  Anderson  Independent  1980   6.6
3    Reagan   Republican  1984  58.8
4   Mondale   Democratic  1984  37.6
5      Bush   Republican  1988  53.4
6   Dukakis   Democratic  1988  45.6
7   Clinton   Democratic  1992  43.0

### Resetting Index

After filtering and sorting, you might want to reset the index to have clean row numbers.

In [ ]:
# Before reset - notice the index numbers
print("Before reset_index:")
print(winners.head(3))

# After reset
winners_reset = winners.reset_index(drop=True)
print("\nAfter reset_index:")
print(winners_reset.head(3))

Before reset_index:
  Candidate       Party     %  Year Result
0    Reagan  Republican  50.7  1980    win
3    Reagan  Republican  58.8  1984    win
5      Bush  Republican  53.4  1988    win

After reset_index:
  Candidate       Party     %  Year Result
0    Reagan  Republican  50.7  1980    win
1    Reagan  Republican  58.8  1984    win
2      Bush  Republican  53.4  1988    win

### 🤔 Your Turn: Practice Filtering and Sorting

**Task 1:** Find all Independent candidates and display their information.

**Task 2:** Find all elections from 2000 or later where the candidate got less than 45% of the vote.

**Task 3:** Sort the elections by candidate name alphabetically and show the first 5 results.

**Task 4:** Create a filtered dataset of Republican candidates, sort them by vote percentage (highest first), and reset the index.

In [ ]:
# Task 1: Find Independent candidates
independents = elections[elections['Party'] == 'Independent']
print("Independent Candidates:")
print(independents)

# Task 2: Elections from 2000+ with <45% votes
filtered = elections[(elections['Year'] >= 2000) & (elections['%'] < 45)]
print("\nElections from 2000+ with <45% votes:")
print(filtered)

# Task 3: Sort by candidate name alphabetically
sorted_candidates = elections.sort_values(by='Candidate')
print("\nCandidates sorted alphabetically:")
print(sorted_candidates)

# Task 4: Filter Republicans, sort by vote percentage, reset index
republicans_sorted = elections[elections['Party'] == 'Republican'].sort_values(by='%', ascending=False).reset_index(drop=True)
print("\nRepublicans sorted by vote percentage:")
print(republicans_sorted)

Independent Candidates:
   Candidate        Party     %  Year Result
2   Anderson  Independent   6.6  1980   loss
9      Perot  Independent  18.9  1992   loss
12     Perot  Independent   8.4  1996   loss

Elections from 2000+ with <45% votes:
Empty DataFrame
Columns: [Candidate, Party, %, Year, Result]
Index: []

Candidates sorted alphabetically:
   Candidate        Party     %  Year Result
2   Anderson  Independent   6.6  1980   loss
16      Bush   Republican  50.7  2004    win
5       Bush   Republican  53.4  1988    win
8       Bush   Republican  37.4  1992   loss
14      Bush   Republican  47.9  2000    win
1     Carter   Democratic  41.0  1980   loss
7    Clinton   Democratic  43.0  1992    win
10   Clinton   Democratic  49.2  1996    win
21   Clinton   Democratic  48.2  2016   loss
11      Dole   Republican  40.7  1996   loss
6    Dukakis   Democratic  45.6  1988   loss
13      Gore   Democratic  48.4  2000   loss
15     Kerry   Democratic  48.3  2004   loss
18    McCain   Republican  45.7  2008   loss
4    Mondale   Democratic  37.6  1984   loss
17     Obama   Democratic  52.9  2008    win
19     Obama   Democratic  51.1  2012    win
12     Perot  Independent   8.4  1996   loss
9      Perot  Independent  18.9  1992   loss
0     Reagan   Republican  50.7  1980    win
3     Reagan   Republican  58.8  1984    win
20    Romney   Republican  47.2  2012   loss
22     Trump   Republican  46.1  2016    win

Republicans sorted by vote percentage:
  Candidate       Party     %  Year Result
0    Reagan  Republican  58.8  1984    win
1      Bush  Republican  53.4  1988    win
2    Reagan  Republican  50.7  1980    win
3      Bush  Republican  50.7  2004    win
4      Bush  Republican  47.9  2000    win
5    Romney  Republican  47.2  2012   loss
6     Trump  Republican  46.1  2016    win
7    McCain  Republican  45.7  2008   loss
8      Dole  Republican  40.7  1996   loss
9      Bush  Republican  37.4  1992   loss

## 6. GroupBy & Aggregations

GroupBy is one of Pandas' most powerful features, allowing you to split data into groups and perform operations on each group.

### Basic GroupBy Operations

Let's group our election data by different categories and see what insights we can find.

In [ ]:
# Group by Party and calculate mean vote percentage
party_stats = elections.groupby('Party')['%'].mean()
print("Average vote percentage by party:")
print(party_stats.sort_values(ascending=False))

Average vote percentage by party:
Party
Republican     47.86
Democratic     46.53
Independent    11.30
Name: %, dtype: float64

In [ ]:
# Count how many times each party appears
party_counts = elections.groupby('Party').size()
print("Number of candidates by party:")
print(party_counts.sort_values(ascending=False))

Number of candidates by party:
Party
Democratic     10
Republican     10
Independent     3
dtype: int64

In [ ]:
# Multiple aggregations at once
party_summary = elections.groupby('Party')['%'].agg(['mean', 'max', 'min', 'count'])
print("Party vote statistics:")
print(party_summary.round(2))

Party vote statistics:
              mean   max   min  count
Party
Democratic   46.53  52.9  37.6     10
Independent  11.30  18.9   6.6      3
Republican   47.86  58.8  37.4     10

### GroupBy with Multiple Columns

You can group by multiple columns to get more detailed insights.

In [ ]:
# Group by Party and Result
party_result = elections.groupby(['Party', 'Result'])['%'].mean()
print("Average vote percentage by party and result:")
print(party_result.round(2))

Average vote percentage by party and result:
Party        Result
Democratic   loss      44.85
             win       49.05
Independent  loss      11.30
Republican   loss      42.75
             win       51.27
Name: %, dtype: float64

In [ ]:
# Convert MultiIndex result to DataFrame for better viewing
party_result_df = party_result.unstack(fill_value=0)
print("Party performance by result (as table):")
print(party_result_df.round(2))

Party performance by result (as table):
Result        loss    win
Party
Democratic   44.85  49.05
Independent  11.30   0.00
Republican   42.75  51.27

### Custom Aggregation Functions

You can also apply custom functions to your grouped data.

In [ ]:
# Custom function to find the range (max - min)
def vote_range(series):
    return series.max() - series.min()

# Apply custom function
party_ranges = elections.groupby('Party')['%'].apply(vote_range)
print("Vote percentage range by party:")
print(party_ranges.round(2))

Vote percentage range by party:
Party
Democratic     15.3
Independent    12.3
Republican     21.4
Name: %, dtype: float64

### 🤔 Your Turn: Practice GroupBy Operations

**Task 1:** Group by 'Result' and calculate the mean vote percentage for winners vs losers.

**Task 2:** Find the maximum vote percentage achieved by each party.

**Task 3:** Group by decade (you'll need to create a decade column first) and count how many elections occurred in each decade.

**Task 4:** Create a custom function that finds the most common candidate name length for each party, then apply it using groupby.

In [ ]:
# Mean vote percentage by result (win/loss)
mean_votes = elections.groupby('Result')['%'].mean()
print("Mean vote percentage by Result:")
print(mean_votes)



# Task 2: YOUR CODE HERE - Max vote percentage by party
max_votes = elections.groupby('Party')['%'].max()
print("\nMaximum vote percentage by Party:")
print(max_votes)

# Task 3: YOUR CODE HERE - Create decade column and count elections per decade
# Create decade column
elections['Decade'] = (elections['Year'] // 10 * 10).astype(int)

# Count elections per decade
elections_per_decade = elections.groupby('Decade').size()
print("\nNumber of elections per decade:")
print(elections_per_decade)

# Task 4: YOUR CODE HERE - Custom function for most common name length by party
# Define a function to get most common name length
def most_common_name_length(names):
    lengths = names.str.len()
    return lengths.mode()[0]  

# Apply function by Party
common_name_length = elections.groupby('Party')['Candidate'].apply(most_common_name_length)
print("\nMost common candidate name length by Party:")
print(common_name_length)

Mean vote percentage by Result:
Result
loss    36.461538
win     50.380000
Name: %, dtype: float64

Maximum vote percentage by Party:
Party
Democratic     52.9
Independent    18.9
Republican     58.8
Name: %, dtype: float64

Number of elections per decade:
Decade
1980    7
1990    6
2000    6
2010    4
dtype: int64

Most common candidate name length by Party:
Party
Democratic     7
Independent    5
Republican     4
Name: Candidate, dtype: int64

## 7. Merging & Joining

Often you'll need to combine data from multiple sources. Pandas provides powerful tools for merging and joining DataFrames.

### Creating Sample DataFrames for Merging

Let's create some additional datasets to demonstrate different types of joins.

In [ ]:
# Create additional datasets to demonstrate merging
candidate_info = pd.DataFrame({
    'Candidate': ['Reagan', 'Carter', 'Clinton', 'Bush', 'Obama'],
    'Age_at_Election': [69, 56, 46, 64, 47],
    'Home_State': ['California', 'Georgia', 'Arkansas', 'Texas', 'Illinois']
})

party_info = pd.DataFrame({
    'Party': ['Democratic', 'Republican', 'Independent'],
    'Founded_Year': [1828, 1854, 1971],
    'Color': ['Blue', 'Red', 'Purple']
})

print("Candidate Info:")
print(candidate_info)
print("\nParty Info:")
print(party_info)

### Inner Join

An inner join returns only rows that have matching values in both DataFrames.

In [ ]:
# Inner join: merge elections with candidate_info
inner_merged = elections.merge(candidate_info, on='Candidate', how='inner')
print("Inner join result (elections + candidate info):")
print(inner_merged[['Candidate', 'Party', 'Year', '%', 'Age_at_Election', 'Home_State']].head())

### Left Join

A left join returns all rows from the left DataFrame and matched rows from the right DataFrame.

In [ ]:
# Left join: keep all elections, add candidate info where available
left_merged = elections.merge(candidate_info, on='Candidate', how='left')
print("Left join result (all elections + candidate info where available):")
print(f"Original elections: {len(elections)} rows")
print(f"After left join: {len(left_merged)} rows")
print("\nSample with missing candidate info:")
print(left_merged[left_merged['Age_at_Election'].isna()][['Candidate', 'Party', 'Year']].head())

In [ ]:
# Merge elections with party_info
party_merged = elections.merge(party_info, on='Party', how='left')
print("Elections with party information:")
print(party_merged[['Candidate', 'Party', 'Year', 'Founded_Year', 'Color']].head())

### Concatenating DataFrames

Sometimes you want to stack DataFrames vertically (adding rows) or horizontally (adding columns).

In [ ]:
# Create two subsets of elections data
elections_1980s = elections[elections['Year'] < 1990]
elections_2000s = elections[elections['Year'] >= 2000]

print("1980s elections:", len(elections_1980s))
print("2000s+ elections:", len(elections_2000s))

# Concatenate vertically (stack rows)
combined_elections = pd.concat([elections_1980s, elections_2000s], axis=0)
print(f"Combined: {len(combined_elections)} rows")
print("\nFirst few rows of combined data:")
print(combined_elections.head())

### 🤔 Your Turn: Practice Merging and Joining

**Task 1:** Create a right join between elections and candidate_info. How many rows do you get?

**Task 2:** Create an outer join between elections and party_info to see all combinations.

**Task 3:** Concatenate the first 5 rows and last 5 rows of the elections dataset.

**Task 4:** Create a new DataFrame with candidate ages, merge it with elections, and find the average age of winners vs losers.

In [ ]:
# Task 1: YOUR CODE HERE - Right join between elections and candidate_info
right_joined = elections.merge(candidate_info, how='right', on='Candidate')
print("Right join with candidate_info:")
print(right_joined.head())

# Task 2: YOUR CODE HERE - Outer join between elections and party_info
outer_joined = elections.merge(party_info, how='outer', on='Party')
print("\nOuter join with party_info:")
print(outer_joined.head())

# Task 3: YOUR CODE HERE - Concatenate first 5 and last 5 rows
first_last = pd.concat([elections.head(5), elections.tail(5)], ignore_index=True)
print("\nConcatenation of first 5 and last 5 rows:")
print(first_last)

# Task 4: YOUR CODE HERE - Create age DataFrame, merge, and compare winner/loser ages
age_data = {
    'Candidate': ['Reagan','Carter','Anderson','Clinton','Bush','Obama','Trump'],
    'Age': [69, 54, 63, 46, 55, 47, 70]
}
ages = pd.DataFrame(age_data)

# Merge with elections
elections_with_age = elections.merge(ages, how='left', on='Candidate')

# Compare winner vs loser ages
age_stats = elections_with_age.groupby('Result')['Age'].mean()
print("\nAverage ages by Result (Winner/Loser):")
print(age_stats)

## 8. Advanced Operations

Let's explore some powerful advanced features: apply functions, lambda expressions, and pivot tables.

### Apply Functions

The `apply()` method allows you to apply a function along an axis of a DataFrame or to each element of a Series.

In [ ]:
# Apply a function to transform vote percentages to decimals
def to_decimal(percentage):
    return percentage / 100

elections['Vote_Decimal'] = elections['%'].apply(to_decimal)
print("Applied function to convert percentages:")
print(elections[['Candidate', '%', 'Vote_Decimal']].head())

In [ ]:
# Apply function row-wise (axis=1) to create new columns
def categorize_performance(row):
    if row['%'] >= 50:
        return 'Strong'
    elif row['%'] >= 40:
        return 'Moderate' 
    else:
        return 'Weak'

elections['Performance'] = elections.apply(categorize_performance, axis=1)
print("Applied row-wise function:")
print(elections[['Candidate', '%', 'Performance']].head())

### Lambda Functions

Lambda functions provide a concise way to write simple functions inline.

In [ ]:
# Using lambda to create candidate name lengths
elections['Name_Length'] = elections['Candidate'].apply(lambda x: len(x))

# Using lambda for more complex operations
elections['Era'] = elections['Year'].apply(lambda year: '1980s' if year < 1990 
                                         else '1990s' if year < 2000
                                         else '2000s' if year < 2010
                                         else '2010s+')

print("Lambda function results:")
print(elections[['Candidate', 'Year', 'Name_Length', 'Era']].head())

### String Operations

Pandas provides powerful string manipulation methods through the `.str` accessor.

In [ ]:
# String operations on candidate names
elections['Candidate_Upper'] = elections['Candidate'].str.upper()
elections['Candidate_Lower'] = elections['Candidate'].str.lower()
elections['Starts_with_R'] = elections['Candidate'].str.startswith('R')

print("String operations:")
print(elections[['Candidate', 'Candidate_Upper', 'Starts_with_R']].head())

### 🤔 Your Turn: Practice Advanced Operations

**Task 1:** Use `apply()` with a lambda function to create a column that shows whether each candidate's vote percentage is above or below the overall average.

**Task 2:** Use string methods to find all candidates whose names contain the letter 'a' (case-insensitive).

**Task 3:** Create a custom function that categorizes elections as 'Landslide' (>55%), 'Clear Win' (50-55%), 'Close' (45-50%), or 'Loss' (<45%), then apply it to create a new column.

In [ ]:
# Calculate average vote percentage
avg_vote = elections['%'].mean()

# Create a new column to classify above/below average
elections['VoteCategory'] = elections['%'].apply(lambda x: 'Above Average' if x > avg_vote else 'Below Average')

print("Elections with above/below average classification:")
print(elections[['Candidate', '%', 'VoteCategory']])

Elections with above/below average classification:
   Candidate     %   VoteCategory
0     Reagan  50.7  Above Average
1     Carter  41.0  Below Average
2   Anderson   6.6  Below Average
3     Reagan  58.8  Above Average
4    Mondale  37.6  Below Average
5       Bush  53.4  Above Average
6    Dukakis  45.6  Above Average
7    Clinton  43.0  Above Average
8       Bush  37.4  Below Average
9      Perot  18.9  Below Average
10   Clinton  49.2  Above Average
11      Dole  40.7  Below Average
12     Perot   8.4  Below Average
13      Gore  48.4  Above Average
14      Bush  47.9  Above Average
15     Kerry  48.3  Above Average
16      Bush  50.7  Above Average
17     Obama  52.9  Above Average
18    McCain  45.7  Above Average
19     Obama  51.1  Above Average
20    Romney  47.2  Above Average
21   Clinton  48.2  Above Average
22     Trump  46.1  Above Average

## 🎉 Congratulations!

You've completed a comprehensive introduction to Pandas! Let's summarize what you've learned:

### Key Concepts Covered:

1. **Introduction** - Understanding what Pandas is and why it's essential for data science
2. **Getting Started** - Importing libraries, loading CSV files, and displaying data
3. **Basic Operations** - Exploring datasets, selecting columns/rows, and managing indexes
4. **Data Cleaning** - Handling missing values, renaming columns, and changing data types
5. **Filtering & Sorting** - Boolean filtering, sorting by multiple columns, and resetting indexes
6. **GroupBy & Aggregations** - Grouping data and performing aggregate operations
7. **Merging & Joining** - Combining datasets with different types of joins
8. **Advanced Operations** - Apply functions, lambda expressions, pivot tables, and string operations

### What's Next?

Now that you have a solid foundation in Pandas, you can:

- **Practice** with real datasets from your field of interest
- **Explore** more advanced features like time series analysis, categorical data, and performance optimization
- **Combine** Pandas with other libraries like Matplotlib for visualization and Scikit-learn for machine learning
- **Work** on data science projects that require data cleaning, analysis, and insights

### Remember:
- Pandas documentation is your friend: https://pandas.pydata.org/docs/
- Practice makes perfect - try these concepts on different datasets
- Don't be afraid to experiment and make mistakes - that's how you learn!